### ISSUE TITLE
chopper2: printed .dynsym symbol names are junk

### ISSUE THREAD

**Issue by xs-exp** [pszostek/cp#8]
Presumably incorrect symbol info (string) is loaded. Test on /bin/bash

`Secn ID Symbol name                              offset         last byte      size (hex)
     14 ٳ\^Of<EE>^GٝZ<E7>^V)<CD>^A ^B<8A><BA>rc<A1>O?@<O<95>%^A,<E7>a6<ED><F2>7<8B><DF>zBl^Wc 0x47f580         0x47f743         452 (0x1c4)
     14 <AA>]^S*<C8><F5><C7>ӹ<93><90>y<C7>^T<DE><E8>N^Q<D9><D4><FB>j<D6>e<DC>h<D5><D9>C<ED>^M<F5><CE>Q<A0>ƴ<84><80>r<AA>Kx^P
<U+058D><B8><9B>)h[(<E0><9F>^ABq<C6><E1>A<B0>*<AA><86><<F4><82>P<86>n<94><D7>-<BE><86><F4>-Ũ<84>:e<82><E9>^BL&Z<D8>2p^Kߧ
<EA>*<E7><E4><E6>^A"^B<D9>輄&<D4>i6w<82><FB>^Y<E0>4c&<<BB>m`<D9>^Y^Q4@<F4>J<E8><95>^V<88><B3><BE>^N<FF><A0>Ҋ:Y<F5>^U<F3><82>y
^V<D3>S^M<90><B0><B8><9F><E6><B6>Y<E9><B5>m<B1>d<F6>t<B6>e<D8><F1>)<F3>ɚ^B<F9><8D><D5><C1>-<81>^\M<E8> N<DC>Wz<96>u<D7>&g<B2>
<99><E2><86>^M^Q<EB>^T^H}<8E><D8><EE><F9>^F<B3>`<CD>/<9E>sH^X<EE><D7>{<F0><F1>`호<95>"J;H<85>ESC,<96>P<FE>5<AB>юDuO^M<93><E3>
<D9><EC>7<C7><CC><E2>d^K<C2><FE>lb<E3><B4><FE><8F><BC>#O<C9>^V<D8>"<BD><AE><C7>Ck<F3>U^Z<A9>uESC<E4><BA>.<F1><A9><9C> 0x439c00         0x439cc6         199 (0xc7)
`

**Comment by pszostek** [comment]
Fixed with 00553aa748ca227afc5b8a2554a23942318c21d4.
